%除去部分野点
function NewData = Smooth(data)

    NewData = zeros(length(data), 1);
    
    NewData(1 : 3) = data(1 : 3);
    for n = 4 : length(data)-3
        if ( ...
                abs(data(n)-data(n-1))>10 && ...
                abs(data(n)-data(n-2))>10 && ...
                abs(data(n)-data(n+1))>10 && ...
                abs(data(n)-data(n+2))>10 ...
            ) || ( ...
                abs(data(n)-data(n-1))>10 && ...
                abs(data(n)-data(n+1))>10 && ...
                abs(data(n)-data(n+2))>10 && ...
                abs(data(n)-data(n+3))>10 ...
            ) || ( ...            
                abs(data(n)-data(n-3))>10 && ...
                abs(data(n)-data(n-2))>10 && ...
                abs(data(n)-data(n-1))>10 && ...
                abs(data(n)-data(n+1))>10 ...
            )
            
            NewData(n) = (data(n-2)+data(n-1)+data(n+1)+data(n+2))/4;
            
        else
            
            NewData(n) = data(n);
            
        end
        
    end

    NewData(n+1 : n+3) = data(n+1 : n+3);

end